[build]
    publish = "public"
    command = "hugo --gc --minify"

[build.environment]
    HUGO_VERSION = "0.134.2"
    HUGO_THEME = "hugo-scroll"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"
